### ISSUE TITLE
Installing Mish

### ISSUE THREAD

**Issue by OAfzal** [ash80/scaledyolov4-cpu#1]
How do I install mish for this repo. I can't install Mish Cuda. My GPU is very old for current PyTorch releases that is why I wanted a CPU version of ScaledYolov4 but this is not working either.

**Comment by ash80** [comment]
This repository doesn't use Mish Cuda. so you shouldn't need to install it.

**Comment by ash80** [comment]
There is a Mish folder that defines mish operation for cpu
